import type { Player } from "./types"

export const EPL_PLAYERS: Player[] = [
  { id: "epl-1", name: "라야", nameEn: "Raya", team: "아스널", teamEn: "Arsenal", position: "GK", cost: 6 },
  { id: "epl-2", name: "피크포드", nameEn: "Pickford", team: "에버턴", teamEn: "Everton", position: "GK", cost: 5.6 },
  { id: "epl-3", name: "도나루마", nameEn: "Donnarumma", team: "맨시티", teamEn: "Man City", position: "GK", cost: 5.6 },
  { id: "epl-4", name: "알리송", nameEn: "A.Becker", team: "리버풀", teamEn: "Liverpool", position: "GK", cost: 5.4 },
  { id: "epl-5", name: "에데르송", nameEn: "Ederson M.", team: "맨시티", teamEn: "Man City", position: "GK", cost: 5.3 },
  { id: "epl-6", name: "마르티네스", nameEn: "Martinez", team: "아스톤 빌라", teamEn: "Aston Villa", position: "GK", cost: 5.1 },
  { id: "epl-7", name: "포프", nameEn: "Pope", team: "뉴캐슬", teamEn: "Newcastle", position: "GK", cost: 5.1 },
  { id: "epl-8", name: "헨더슨", nameEn: "Henderson", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "GK", cost: 5 },
  { id: "epl-9", name: "라멘스", nameEn: "Lammens", team: "맨유", teamEn: "Man Utd", position: "GK", cost: 5 },
  { id: "epl-10", name: "산체스", nameEn: "Sánchez", team: "첼시", teamEn: "Chelsea", position: "GK", cost: 4.9 },
  { id: "epl-11", name: "레노", nameEn: "Leno", team: "풀럼", teamEn: "Fulham", position: "GK", cost: 4.9 },
  { id: "epl-12", name: "오나나", nameEn: "Onana", team: "맨유", teamEn: "Man Utd", position: "GK", cost: 4.9 },
  { id: "epl-13", name: "루프스", nameEn: "Roefs", team: "선덜랜드", teamEn: "Sunderland", position: "GK", cost: 4.9 },
  { id: "epl-14", name: "램즈데일", nameEn: "Ramsdale", team: "뉴캐슬", teamEn: "Newcastle", position: "GK", cost: 4.8 },
  { id: "epl-15", name: "켈러허", nameEn: "Kelleher", team: "브렌트퍼드", teamEn: "Brentford", position: "GK", cost: 4.7 },
  { id: "epl-16", name: "오르테가", nameEn: "Ortega Moreno", team: "노팅엄", teamEn: "Nott'm Forest", position: "GK", cost: 4.7 },
  { id: "epl-17", name: "바인디르", nameEn: "Bayindir", team: "맨유", teamEn: "Man Utd", position: "GK", cost: 4.7 },
  { id: "epl-18", name: "비카리오", nameEn: "Vicario", team: "토트넘", teamEn: "Spurs", position: "GK", cost: 4.7 },
  { id: "epl-19", name: "셀스", nameEn: "Sels", team: "노팅엄", teamEn: "Nott'm Forest", position: "GK", cost: 4.6 },
  { id: "epl-20", name: "네투", nameEn: "Neto", team: "본머스", teamEn: "Bournemouth", position: "GK", cost: 4.5 },
  { id: "epl-21", name: "페트로비치", nameEn: "Petrović", team: "본머스", teamEn: "Bournemouth", position: "GK", cost: 4.5 },
  { id: "epl-22", name: "페르브뤼헌", nameEn: "Verbruggen", team: "브라이턴", teamEn: "Brighton", position: "GK", cost: 4.5 },
  { id: "epl-23", name: "트래포드", nameEn: "Trafford", team: "맨시티", teamEn: "Man City", position: "GK", cost: 4.5 },
  { id: "epl-24", name: "페리", nameEn: "Perri", team: "리즈", teamEn: "Leeds", position: "GK", cost: 4.5 },
  { id: "epl-25", name: "파비안스키", nameEn: "Fabianski", team: "웨스트햄", teamEn: "West Ham", position: "GK", cost: 4.5 },
  { id: "epl-26", name: "존스턴", nameEn: "Johnstone", team: "울버햄턴", teamEn: "Wolves", position: "GK", cost: 4.4 },
  { id: "epl-27", name: "바이스", nameEn: "Weiss", team: "번리", teamEn: "Burnley", position: "GK", cost: 4.3 },
  { id: "epl-28", name: "예르옌센", nameEn: "Jörgensen", team: "첼시", teamEn: "Chelsea", position: "GK", cost: 4.3 },
  { id: "epl-29", name: "트래버스", nameEn: "Travers", team: "에버턴", teamEn: "Everton", position: "GK", cost: 4.3 },
  { id: "epl-30", name: "아레올라", nameEn: "Areola", team: "웨스트햄", teamEn: "West Ham", position: "GK", cost: 4.3 },
  { id: "epl-31", name: "비조", nameEn: "M.Bizot", team: "아스톤 빌라", teamEn: "Aston Villa", position: "GK", cost: 4.2 },
  { id: "epl-32", name: "스틸", nameEn: "Steele", team: "브라이턴", teamEn: "Brighton", position: "GK", cost: 4.2 },
  { id: "epl-33", name: "패터슨", nameEn: "Patterson", team: "선덜랜드", teamEn: "Sunderland", position: "GK", cost: 4.2 },
  { id: "epl-34", name: "조제 사", nameEn: "José Sá", team: "울버햄턴", teamEn: "Wolves", position: "GK", cost: 4.2 },
  { id: "epl-35", name: "헤르만센", nameEn: "Hermansen", team: "웨스트햄", teamEn: "West Ham", position: "GK", cost: 4.2 },
  { id: "epl-36", name: "케파", nameEn: "Arrizabalaga", team: "아스널", teamEn: "Arsenal", position: "GK", cost: 4.1 },
  { id: "epl-37", name: "메슬리에", nameEn: "Meslier", team: "리즈", teamEn: "Leeds", position: "GK", cost: 4.1 },
  { id: "epl-38", name: "마마르다슈빌리", nameEn: "Mamardashvili", team: "리버풀", teamEn: "Liverpool", position: "GK", cost: 4.1 },
  { id: "epl-39", name: "하인", nameEn: "Hein", team: "아스널", teamEn: "Arsenal", position: "GK", cost: 4 },
  { id: "epl-40", name: "가우치", nameEn: "Gauci", team: "아스톤 빌라", teamEn: "Aston Villa", position: "GK", cost: 4 },
  { id: "epl-41", name: "마샬", nameEn: "Marschall", team: "아스톤 빌라", teamEn: "Aston Villa", position: "GK", cost: 4 },
  { id: "epl-42", name: "데니스", nameEn: "Dennis", team: "본머스", teamEn: "Bournemouth", position: "GK", cost: 4 },
  { id: "epl-43", name: "폴센", nameEn: "Paulsen", team: "본머스", teamEn: "Bournemouth", position: "GK", cost: 4 },
  { id: "epl-44", name: "러시워스", nameEn: "Rushworth", team: "브라이턴", teamEn: "Brighton", position: "GK", cost: 4 },
  { id: "epl-45", name: "스헤르펜", nameEn: "Scherpen", team: "브라이턴", teamEn: "Brighton", position: "GK", cost: 4 },
  { id: "epl-46", name: "그린", nameEn: "Green", team: "번리", teamEn: "Burnley", position: "GK", cost: 4 },
  { id: "epl-47", name: "펜더스", nameEn: "Penders", team: "첼시", teamEn: "Chelsea", position: "GK", cost: 4 },
  { id: "epl-48", name: "베니테스", nameEn: "Benitez", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "GK", cost: 4 },
  { id: "epl-49", name: "벤다", nameEn: "Benda", team: "풀럼", teamEn: "Fulham", position: "GK", cost: 4 },
  { id: "epl-50", name: "해리슨", nameEn: "Harrison", team: "맨유", teamEn: "Man Utd", position: "GK", cost: 4 },
  { id: "epl-51", name: "두브라프카", nameEn: "Dúbravka", team: "번리", teamEn: "Burnley", position: "GK", cost: 4 },
  { id: "epl-52", name: "오디세아스", nameEn: "Odysseas", team: "뉴캐슬", teamEn: "Newcastle", position: "GK", cost: 4 },
  { id: "epl-53", name: "미겔", nameEn: "C.Miguel", team: "노팅엄", teamEn: "Nott'm Forest", position: "GK", cost: 4 },
  { id: "epl-54", name: "터너", nameEn: "Turner", team: "노팅엄", teamEn: "Nott'm Forest", position: "GK", cost: 4 },
  { id: "epl-55", name: "포더링엄", nameEn: "Foderingham", team: "웨스트햄", teamEn: "West Ham", position: "GK", cost: 4 },
  { id: "epl-56", name: "건", nameEn: "Gunn", team: "노팅엄", teamEn: "Nott'm Forest", position: "GK", cost: 4 },
  { id: "epl-57", name: "존", nameEn: "John", team: "노팅엄", teamEn: "Nott'm Forest", position: "GK", cost: 4 },
  { id: "epl-58", name: "러디", nameEn: "Ruddy", team: "뉴캐슬", teamEn: "Newcastle", position: "GK", cost: 4 },
  { id: "epl-59", name: "홀링스헤드", nameEn: "Hollingshead", team: "아스톤 빌라", teamEn: "Aston Villa", position: "GK", cost: 4 },
  { id: "epl-60", name: "포스터", nameEn: "Forster", team: "본머스", teamEn: "Bournemouth", position: "GK", cost: 4 },
  { id: "epl-61", name: "맥널리", nameEn: "McNally", team: "풀럼", teamEn: "Fulham", position: "GK", cost: 4 },
  { id: "epl-62", name: "메릭", nameEn: "Merrick", team: "첼시", teamEn: "Chelsea", position: "GK", cost: 4 },
  { id: "epl-63", name: "샤먼로우", nameEn: "Sharman-Lowe", team: "첼시", teamEn: "Chelsea", position: "GK", cost: 4 },
  { id: "epl-64", name: "만다스", nameEn: "Mandas", team: "본머스", teamEn: "Bournemouth", position: "GK", cost: 4 },
  { id: "epl-65", name: "엘보리", nameEn: "Ellborg", team: "선덜랜드", teamEn: "Sunderland", position: "GK", cost: 4 },
  { id: "epl-66", name: "셋포드", nameEn: "Setford", team: "아스널", teamEn: "Arsenal", position: "GK", cost: 3.9 },
  { id: "epl-67", name: "맥케나", nameEn: "McKenna", team: "본머스", teamEn: "Bournemouth", position: "GK", cost: 3.9 },
  { id: "epl-68", name: "발컴", nameEn: "Balcombe", team: "브렌트퍼드", teamEn: "Brentford", position: "GK", cost: 3.9 },
  { id: "epl-69", name: "콕스", nameEn: "Cox", team: "브렌트퍼드", teamEn: "Brentford", position: "GK", cost: 3.9 },
  { id: "epl-70", name: "아이스톤", nameEn: "Eyestone", team: "브렌트퍼드", teamEn: "Brentford", position: "GK", cost: 3.9 },
  { id: "epl-71", name: "발디마르손", nameEn: "Valdimarsson", team: "브렌트퍼드", teamEn: "Brentford", position: "GK", cost: 3.9 },
  { id: "epl-72", name: "맥길", nameEn: "McGill", team: "브라이턴", teamEn: "Brighton", position: "GK", cost: 3.9 },
  { id: "epl-73", name: "흘라드키", nameEn: "Hladký", team: "번리", teamEn: "Burnley", position: "GK", cost: 3.9 },
  { id: "epl-74", name: "슬로니나", nameEn: "Slonina", team: "첼시", teamEn: "Chelsea", position: "GK", cost: 3.9 },
  { id: "epl-75", name: "매튜스", nameEn: "Matthews", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "GK", cost: 3.9 },
  { id: "epl-76", name: "타이러", nameEn: "Tyrer", team: "에버턴", teamEn: "Everton", position: "GK", cost: 3.9 },
  { id: "epl-77", name: "케언스", nameEn: "Cairns", team: "리즈", teamEn: "Leeds", position: "GK", cost: 3.9 },
  { id: "epl-78", name: "달로", nameEn: "Darlow", team: "리즈", teamEn: "Leeds", position: "GK", cost: 3.9 },
  { id: "epl-79", name: "우드먼", nameEn: "Woodman", team: "리버풀", teamEn: "Liverpool", position: "GK", cost: 3.9 },
  { id: "epl-80", name: "히턴", nameEn: "Heaton", team: "맨유", teamEn: "Man Utd", position: "GK", cost: 3.9 },
  { id: "epl-81", name: "미", nameEn: "Mee", team: "맨유", teamEn: "Man Utd", position: "GK", cost: 3.9 },
  { id: "epl-82", name: "길레스피", nameEn: "Gillespie", team: "뉴캐슬", teamEn: "Newcastle", position: "GK", cost: 3.9 },
  { id: "epl-83", name: "무어", nameEn: "Moore", team: "선덜랜드", teamEn: "Sunderland", position: "GK", cost: 3.9 },
  { id: "epl-84", name: "나 누케우", nameEn: "Nna Noukeu", team: "선덜랜드", teamEn: "Sunderland", position: "GK", cost: 3.9 },
  { id: "epl-85", name: "오스틴", nameEn: "Austin", team: "토트넘", teamEn: "Spurs", position: "GK", cost: 3.9 },
  { id: "epl-86", name: "킨스키", nameEn: "Kinsky", team: "토트넘", teamEn: "Spurs", position: "GK", cost: 3.9 },
  { id: "epl-87", name: "헤지", nameEn: "Hegyi", team: "웨스트햄", teamEn: "West Ham", position: "GK", cost: 3.9 },
  { id: "epl-88", name: "벤틀리", nameEn: "Bentley", team: "울버햄턴", teamEn: "Wolves", position: "GK", cost: 3.9 },
  { id: "epl-89", name: "킹", nameEn: "King", team: "에버턴", teamEn: "Everton", position: "GK", cost: 3.9 },
  { id: "epl-90", name: "르콩트", nameEn: "Lecomte", team: "풀럼", teamEn: "Fulham", position: "GK", cost: 3.9 },
  { id: "epl-91", name: "라이트", nameEn: "Wright", team: "아스톤 빌라", teamEn: "Aston Villa", position: "GK", cost: 3.9 },
  { id: "epl-92", name: "프록터", nameEn: "Proctor", team: "아스톤 빌라", teamEn: "Aston Villa", position: "GK", cost: 3.9 },
  { id: "epl-93", name: "페치", nameEn: "Pécsi", team: "리버풀", teamEn: "Liverpool", position: "GK", cost: 3.8 },
  { id: "epl-94", name: "베티넬리", nameEn: "Bettinelli", team: "맨시티", teamEn: "Man City", position: "GK", cost: 3.8 },
  { id: "epl-95", name: "가브리엘", nameEn: "Gabriel", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 7.1 },
  { id: "epl-96", name: "팀버", nameEn: "J.Timber", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 6.3 },
  { id: "epl-97", name: "살리바", nameEn: "Saliba", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 6.1 },
  { id: "epl-98", name: "판데이크", nameEn: "Virgil", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 6.1 },
  { id: "epl-99", name: "쿠쿠렐라", nameEn: "Cucurella", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 6 },
  { id: "epl-100", name: "무뇨스", nameEn: "Muñoz", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 5.9 },
  { id: "epl-101", name: "그바르디올", nameEn: "Gvardiol", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5.9 },
  { id: "epl-102", name: "타르코프스키", nameEn: "Tarkowski", team: "에버턴", teamEn: "Everton", position: "DF", cost: 5.7 },
  { id: "epl-103", name: "프림퐁", nameEn: "Frimpong", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 5.7 },
  { id: "epl-104", name: "로버트슨", nameEn: "Robertson", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 5.7 },
  { id: "epl-105", name: "아이트누리", nameEn: "Aït-Nouri", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5.7 },
  { id: "epl-106", name: "칼라피오리", nameEn: "Calafiori", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 5.6 },
  { id: "epl-107", name: "제임스", nameEn: "James", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 5.6 },
  { id: "epl-108", name: "찰로바", nameEn: "Chalobah", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 5.6 },
  { id: "epl-109", name: "케르케스", nameEn: "Kerkez", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 5.6 },
  { id: "epl-110", name: "코나테", nameEn: "Konaté", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 5.5 },
  { id: "epl-111", name: "루벤 디아스", nameEn: "Rúben", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5.5 },
  { id: "epl-112", name: "키비오르", nameEn: "Kiwior", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 5.4 },
  { id: "epl-113", name: "아칸지", nameEn: "Akanji", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5.4 },
  { id: "epl-114", name: "후사노프", nameEn: "Khusanov", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5.4 },
  { id: "epl-115", name: "마테우스 누네스", nameEn: "Matheus N.", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5.4 },
  { id: "epl-116", name: "스톤스", nameEn: "Stones", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5.4 },
  { id: "epl-117", name: "브랜스웨이트", nameEn: "Branthwaite", team: "에버턴", teamEn: "Everton", position: "DF", cost: 5.3 },
  { id: "epl-118", name: "홀", nameEn: "Hall", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 5.3 },
  { id: "epl-119", name: "모스케라", nameEn: "Mosquera", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 5.3 },
  { id: "epl-120", name: "게이", nameEn: "Guéhi", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5.2 },
  { id: "epl-121", name: "아케", nameEn: "Aké", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5.2 },
  { id: "epl-122", name: "셰어", nameEn: "Schär", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 5.2 },
  { id: "epl-123", name: "무리요", nameEn: "Murillo", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 5.2 },
  { id: "epl-124", name: "루이스스켈리", nameEn: "Lewis-Skelly", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 5.1 },
  { id: "epl-125", name: "화이트", nameEn: "White", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 5.1 },
  { id: "epl-126", name: "라크루아", nameEn: "Lacroix", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 5.1 },
  { id: "epl-127", name: "오라일리", nameEn: "O'Reilly", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5.1 },
  { id: "epl-128", name: "밀렌코비치", nameEn: "Milenković", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 5.1 },
  { id: "epl-129", name: "페드로 포로", nameEn: "Pedro Porro", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 5.1 },
  { id: "epl-130", name: "인카피에", nameEn: "Hincapie", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 5.1 },
  { id: "epl-131", name: "자바르니", nameEn: "Zabarnyi", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 5 },
  { id: "epl-132", name: "미첼", nameEn: "Mitchell", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 5 },
  { id: "epl-133", name: "비토르 헤이스", nameEn: "Vitor Reis", team: "맨시티", teamEn: "Man City", position: "DF", cost: 5 },
  { id: "epl-134", name: "번", nameEn: "Burn", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 5 },
  { id: "epl-135", name: "로메로", nameEn: "Romero", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 5 },
  { id: "epl-136", name: "티아우", nameEn: "Thiaw", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 5 },
  { id: "epl-137", name: "진첸코", nameEn: "Zinchenko", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 4.9 },
  { id: "epl-138", name: "세네시", nameEn: "Senesi", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 4.9 },
  { id: "epl-139", name: "콜린스", nameEn: "Collins", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4.9 },
  { id: "epl-140", name: "구스토", nameEn: "Gusto", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 4.9 },
  { id: "epl-141", name: "미콜렌코", nameEn: "Mykolenko", team: "에버턴", teamEn: "Everton", position: "DF", cost: 4.9 },
  { id: "epl-142", name: "오브라이언", nameEn: "O'Brien", team: "에버턴", teamEn: "Everton", position: "DF", cost: 4.9 },
  { id: "epl-143", name: "로빈슨", nameEn: "Robinson", team: "풀럼", teamEn: "Fulham", position: "DF", cost: 4.9 },
  { id: "epl-144", name: "브래들리", nameEn: "Bradley", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 4.9 },
  { id: "epl-145", name: "고메스", nameEn: "Gomez", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 4.9 },
  { id: "epl-146", name: "더리흐트", nameEn: "De Ligt", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4.9 },
  { id: "epl-147", name: "마즈라위", nameEn: "Mazraoui", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4.9 },
  { id: "epl-148", name: "보트만", nameEn: "Botman", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 4.9 },
  { id: "epl-149", name: "리브라멘투", nameEn: "Livramento", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 4.9 },
  { id: "epl-150", name: "트리피어", nameEn: "Trippier", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 4.9 },
  { id: "epl-151", name: "레오니", nameEn: "Leoni", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 4.9 },
  { id: "epl-152", name: "캐시", nameEn: "Cash", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4.8 },
  { id: "epl-153", name: "루이스포터", nameEn: "Lewis-Potter", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4.8 },
  { id: "epl-154", name: "소사", nameEn: "Sosa", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 4.8 },
  { id: "epl-155", name: "치미카스", nameEn: "Tsimikas", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 4.8 },
  { id: "epl-156", name: "마르티네스", nameEn: "Martinez", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4.8 },
  { id: "epl-157", name: "콜윌", nameEn: "Colwill", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 4.7 },
  { id: "epl-158", name: "아이나", nameEn: "Aina", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 4.7 },
  { id: "epl-159", name: "윌리엄스", nameEn: "N.Williams", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 4.7 },
  { id: "epl-160", name: "트뤼페르", nameEn: "Truffert", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 4.6 },
  { id: "epl-161", name: "킨", nameEn: "Keane", team: "에버턴", teamEn: "Everton", position: "DF", cost: 4.6 },
  { id: "epl-162", name: "루이스", nameEn: "Lewis", team: "맨시티", teamEn: "Man City", position: "DF", cost: 4.6 },
  { id: "epl-163", name: "달로트", nameEn: "Dalot", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4.6 },
  { id: "epl-164", name: "발라드", nameEn: "Ballard", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4.6 },
  { id: "epl-165", name: "하토", nameEn: "Hato", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 4.6 },
  { id: "epl-166", name: "디뉴", nameEn: "Digne", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4.5 },
  { id: "epl-167", name: "카요데", nameEn: "Kayode", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4.5 },
  { id: "epl-168", name: "뢰르슬레우", nameEn: "Roerslev", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4.5 },
  { id: "epl-169", name: "판덴베르흐", nameEn: "Van den Berg", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4.5 },
  { id: "epl-170", name: "덩크", nameEn: "Dunk", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.5 },
  { id: "epl-171", name: "에스투피냔", nameEn: "Estupiñan", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.5 },
  { id: "epl-172", name: "이고르", nameEn: "Igor", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.5 },
  { id: "epl-173", name: "사르", nameEn: "M.Sarr", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 4.5 },
  { id: "epl-174", name: "안데르센", nameEn: "Andersen", team: "풀럼", teamEn: "Fulham", position: "DF", cost: 4.5 },
  { id: "epl-175", name: "테테", nameEn: "Tete", team: "풀럼", teamEn: "Fulham", position: "DF", cost: 4.5 },
  { id: "epl-176", name: "쇼", nameEn: "Shaw", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4.5 },
  { id: "epl-177", name: "다비드 카르무", nameEn: "David Carmo", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 4.5 },
  { id: "epl-178", name: "리처즈", nameEn: "O.Richards", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 4.5 },
  { id: "epl-179", name: "흄", nameEn: "Hume", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4.5 },
  { id: "epl-180", name: "드라구신", nameEn: "Dragusin", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4.5 },
  { id: "epl-181", name: "뮈키엘레", nameEn: "Mukiele", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4.5 },
  { id: "epl-182", name: "크레이치", nameEn: "Krejčí", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4.5 },
  { id: "epl-183", name: "히메네스", nameEn: "A.Jimenez", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 4.5 },
  { id: "epl-184", name: "사보나", nameEn: "Savona", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 4.5 },
  { id: "epl-185", name: "린델뢰프", nameEn: "Lindelöf", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4.5 },
  { id: "epl-186", name: "캉보", nameEn: "Canvot", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 4.5 },
  { id: "epl-187", name: "헤이르트라위다", nameEn: "Geertruida", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4.5 },
  { id: "epl-188", name: "쿠이아바누", nameEn: "Cuiabano", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 4.5 },
  { id: "epl-189", name: "네츠", nameEn: "Netz", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 4.5 },
  { id: "epl-190", name: "디사시", nameEn: "Disasi", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4.5 },
  { id: "epl-191", name: "콘사", nameEn: "Konsa", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4.4 },
  { id: "epl-192", name: "스미스", nameEn: "Smith", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 4.4 },
  { id: "epl-193", name: "아예르", nameEn: "Ajer", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4.4 },
  { id: "epl-194", name: "카디올루", nameEn: "F.Kadıoğlu", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.4 },
  { id: "epl-195", name: "램프티", nameEn: "Lamptey", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.4 },
  { id: "epl-196", name: "판헤커", nameEn: "Van Hecke", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.4 },
  { id: "epl-197", name: "웹스터", nameEn: "Webster", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.4 },
  { id: "epl-198", name: "로버츠", nameEn: "Roberts", team: "번리", teamEn: "Burnley", position: "DF", cost: 4.4 },
  { id: "epl-199", name: "워커", nameEn: "Walker", team: "번리", teamEn: "Burnley", position: "DF", cost: 4.4 },
  { id: "epl-200", name: "바디아실", nameEn: "B.Badiashile", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 4.4 },
  { id: "epl-201", name: "포파나", nameEn: "Fofana", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 4.4 },
  { id: "epl-202", name: "리처즈", nameEn: "Richards", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 4.4 },
  { id: "epl-203", name: "패터슨", nameEn: "Patterson", team: "에버턴", teamEn: "Everton", position: "DF", cost: 4.4 },
  { id: "epl-204", name: "바세이", nameEn: "Bassey", team: "풀럼", teamEn: "Fulham", position: "DF", cost: 4.4 },
  { id: "epl-205", name: "보글", nameEn: "Bogle", team: "리즈", teamEn: "Leeds", position: "DF", cost: 4.4 },
  { id: "epl-206", name: "매과이어", nameEn: "Maguire", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4.4 },
  { id: "epl-207", name: "판더번", nameEn: "Van de Ven", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4.4 },
  { id: "epl-208", name: "에머슨", nameEn: "Emerson", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4.4 },
  { id: "epl-209", name: "마브로파노스", nameEn: "Mavropanos", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4.4 },
  { id: "epl-210", name: "아게르", nameEn: "N.Aguerd", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4.4 },
  { id: "epl-211", name: "도허티", nameEn: "Doherty", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4.4 },
  { id: "epl-212", name: "고메스", nameEn: "R.Gomes", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4.4 },
  { id: "epl-213", name: "부에노", nameEn: "S.Bueno", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4.4 },
  { id: "epl-214", name: "차추아", nameEn: "Tchatchoua", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4.4 },
  { id: "epl-215", name: "밀로사블예비치", nameEn: "Milosavljević", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 4.4 },
  { id: "epl-216", name: "밍스", nameEn: "Mings", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4.3 },
  { id: "epl-217", name: "파우", nameEn: "Pau", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4.3 },
  { id: "epl-218", name: "헨리", nameEn: "Henry", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4.3 },
  { id: "epl-219", name: "더카위퍼", nameEn: "De Cuyper", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.3 },
  { id: "epl-220", name: "벨트만", nameEn: "Veltman", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.3 },
  { id: "epl-221", name: "카스타뉴", nameEn: "Castagne", team: "풀럼", teamEn: "Fulham", position: "DF", cost: 4.3 },
  { id: "epl-222", name: "디옵", nameEn: "Diop", team: "풀럼", teamEn: "Fulham", position: "DF", cost: 4.3 },
  { id: "epl-223", name: "쿠엔카", nameEn: "J.Cuenca", team: "풀럼", teamEn: "Fulham", position: "DF", cost: 4.3 },
  { id: "epl-224", name: "스트라위크", nameEn: "Struijk", team: "리즈", teamEn: "Leeds", position: "DF", cost: 4.3 },
  { id: "epl-225", name: "크라프트", nameEn: "Krafth", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 4.3 },
  { id: "epl-226", name: "라셀스", nameEn: "Lascelles", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 4.3 },
  { id: "epl-227", name: "모라투", nameEn: "Morato", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 4.3 },
  { id: "epl-228", name: "데이비스", nameEn: "Davies", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4.3 },
  { id: "epl-229", name: "우도지에", nameEn: "Udogie", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4.3 },
  { id: "epl-230", name: "스칼스", nameEn: "Scarles", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4.3 },
  { id: "epl-231", name: "토디보", nameEn: "Todibo", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4.3 },
  { id: "epl-232", name: "부에노", nameEn: "H.Bueno", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4.3 },
  { id: "epl-233", name: "모스케라", nameEn: "Mosquera", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4.3 },
  { id: "epl-234", name: "마트센", nameEn: "Maatsen", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4.2 },
  { id: "epl-235", name: "피녹", nameEn: "Pinnock", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4.2 },
  { id: "epl-236", name: "보스칼리", nameEn: "Boscagli", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.2 },
  { id: "epl-237", name: "코폴라", nameEn: "Coppola", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4.2 },
  { id: "epl-238", name: "콜먼", nameEn: "Coleman", team: "에버턴", teamEn: "Everton", position: "DF", cost: 4.2 },
  { id: "epl-239", name: "레온", nameEn: "D.Leon", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4.2 },
  { id: "epl-240", name: "도르구", nameEn: "Dorgu", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4.2 },
  { id: "epl-241", name: "자이르 쿠냐", nameEn: "Jair Cunha", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 4.2 },
  { id: "epl-242", name: "단소", nameEn: "Danso", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4.2 },
  { id: "epl-243", name: "스펜스", nameEn: "Spence", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4.2 },
  { id: "epl-244", name: "아그바두", nameEn: "Agbadou", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4.2 },
  { id: "epl-245", name: "토티", nameEn: "Toti", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4.2 },
  { id: "epl-246", name: "워커피터스", nameEn: "Walker-Peters", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4.2 },
  { id: "epl-247", name: "아즈누", nameEn: "Aznou", team: "에버턴", teamEn: "Everton", position: "DF", cost: 4.2 },
  { id: "epl-248", name: "묄러 울프", nameEn: "Møller Wolfe", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4.2 },
  { id: "epl-249", name: "디아키테", nameEn: "Diakité", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 4.2 },
  { id: "epl-250", name: "힐", nameEn: "Hill", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 4.1 },
  { id: "epl-251", name: "요로", nameEn: "Yoro", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4.1 },
  { id: "epl-252", name: "킬먼", nameEn: "Kilman", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4.1 },
  { id: "epl-253", name: "완비사카", nameEn: "Wan-Bissaka", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4.1 },
  { id: "epl-254", name: "알데레테", nameEn: "Alderete", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4.1 },
  { id: "epl-255", name: "알렉스 모레노", nameEn: "Alex Moreno", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4 },
  { id: "epl-256", name: "보가르더", nameEn: "Bogarde", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4 },
  { id: "epl-257", name: "야신", nameEn: "Yasin", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4 },
  { id: "epl-258", name: "메팸", nameEn: "Mepham", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 4 },
  { id: "epl-259", name: "솔레르", nameEn: "Soler", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 4 },
  { id: "epl-260", name: "프레드릭", nameEn: "Fredrick", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4 },
  { id: "epl-261", name: "히키", nameEn: "Hickey", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4 },
  { id: "epl-262", name: "메고마", nameEn: "Meghoma", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4 },
  { id: "epl-263", name: "캐신", nameEn: "Cashin", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4 },
  { id: "epl-264", name: "슬레이터", nameEn: "Slater", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4 },
  { id: "epl-265", name: "도지슨", nameEn: "Dodgson", team: "번리", teamEn: "Burnley", position: "DF", cost: 4 },
  { id: "epl-266", name: "하트만", nameEn: "Hartman", team: "번리", teamEn: "Burnley", position: "DF", cost: 4 },
  { id: "epl-267", name: "삼보", nameEn: "Sambo", team: "번리", teamEn: "Burnley", position: "DF", cost: 4 },
  { id: "epl-268", name: "토신", nameEn: "Tosin", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 4 },
  { id: "epl-269", name: "안셀미노", nameEn: "Anselmino", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 4 },
  { id: "epl-270", name: "샤디 리아드", nameEn: "Chadi Riad", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 4 },
  { id: "epl-271", name: "홀딩", nameEn: "Holding", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 4 },
  { id: "epl-272", name: "크포르하", nameEn: "Kporha", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 4 },
  { id: "epl-273", name: "슈미트", nameEn: "Schmidt", team: "리즈", teamEn: "Leeds", position: "DF", cost: 4 },
  { id: "epl-274", name: "아마스", nameEn: "Amass", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4 },
  { id: "epl-275", name: "타겟", nameEn: "Targett", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 4 },
  { id: "epl-276", name: "알레세", nameEn: "Alese", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4 },
  { id: "epl-277", name: "서킨", nameEn: "Cirkin", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4 },
  { id: "epl-278", name: "옐데", nameEn: "Hjelde", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4 },
  { id: "epl-279", name: "허긴스", nameEn: "Huggins", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4 },
  { id: "epl-280", name: "오니언", nameEn: "O'Nien", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4 },
  { id: "epl-281", name: "셀트", nameEn: "Seelt", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4 },
  { id: "epl-282", name: "필립스", nameEn: "Phillips", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4 },
  { id: "epl-283", name: "타카이", nameEn: "Takai", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4 },
  { id: "epl-284", name: "디우프", nameEn: "Diouf", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4 },
  { id: "epl-285", name: "케이시", nameEn: "Casey", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4 },
  { id: "epl-286", name: "뫼피유", nameEn: "Meupiyou", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4 },
  { id: "epl-287", name: "페드루 리마", nameEn: "Pedro Lima", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4 },
  { id: "epl-288", name: "로우", nameEn: "Rowe", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4 },
  { id: "epl-289", name: "바이필드", nameEn: "Byfield", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4 },
  { id: "epl-290", name: "메이어스", nameEn: "Mayers", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4 },
  { id: "epl-291", name: "로스웰", nameEn: "Rowswell", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4 },
  { id: "epl-292", name: "골람베키스", nameEn: "Golambeckis", team: "웨스트햄", teamEn: "West Ham", position: "DF", cost: 4 },
  { id: "epl-293", name: "새먼", nameEn: "Salmon", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 4 },
  { id: "epl-294", name: "럭키", nameEn: "Lucky", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 4 },
  { id: "epl-295", name: "시몬즈", nameEn: "Simmonds", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 4 },
  { id: "epl-296", name: "샤하르", nameEn: "Shahar", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 4 },
  { id: "epl-297", name: "올라군주", nameEn: "Olagunju", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 4 },
  { id: "epl-298", name: "레온 라우스", nameEn: "Leon Routh", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4 },
  { id: "epl-299", name: "베나마르", nameEn: "Benamar", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 4 },
  { id: "epl-300", name: "젠슨 존스", nameEn: "Jenson Jones", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 4 },
  { id: "epl-301", name: "캐럴", nameEn: "Carroll", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 4 },
  { id: "epl-302", name: "쿠콘키", nameEn: "Kukonki", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 4 },
  { id: "epl-303", name: "킹", nameEn: "King", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 4 },
  { id: "epl-304", name: "알레인", nameEn: "Alleyne", team: "맨시티", teamEn: "Man City", position: "DF", cost: 4 },
  { id: "epl-305", name: "임레이", nameEn: "Imray", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 4 },
  { id: "epl-306", name: "소우자", nameEn: "Souza", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 4 },
  { id: "epl-307", name: "실드", nameEn: "Shield", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 4 },
  { id: "epl-308", name: "카쿠리", nameEn: "Kacurri", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 3.9 },
  { id: "epl-309", name: "가르시아", nameEn: "A.García", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 3.9 },
  { id: "epl-310", name: "지수", nameEn: "Ji-soo", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 3.9 },
  { id: "epl-311", name: "에크달", nameEn: "Ekdal", team: "번리", teamEn: "Burnley", position: "DF", cost: 3.9 },
  { id: "epl-312", name: "에스테브", nameEn: "Estève", team: "번리", teamEn: "Burnley", position: "DF", cost: 3.9 },
  { id: "epl-313", name: "험프리스", nameEn: "Humphreys", team: "번리", teamEn: "Burnley", position: "DF", cost: 3.9 },
  { id: "epl-314", name: "조던", nameEn: "Jordan", team: "번리", teamEn: "Burnley", position: "DF", cost: 3.9 },
  { id: "epl-315", name: "투안제베", nameEn: "Tuanzebe", team: "번리", teamEn: "Burnley", position: "DF", cost: 3.9 },
  { id: "epl-316", name: "비욜", nameEn: "Bijol", team: "리즈", teamEn: "Leeds", position: "DF", cost: 3.9 },
  { id: "epl-317", name: "로던", nameEn: "Rodon", team: "리즈", teamEn: "Leeds", position: "DF", cost: 3.9 },
  { id: "epl-318", name: "애시비", nameEn: "Ashby", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 3.9 },
  { id: "epl-319", name: "팡벨레", nameEn: "Pembele", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 3.9 },
  { id: "epl-320", name: "부스코비치", nameEn: "Vuskovic", team: "토트넘", teamEn: "Spurs", position: "DF", cost: 3.9 },
  { id: "epl-321", name: "폰드", nameEn: "Pond", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 3.9 },
  { id: "epl-322", name: "마수아쿠", nameEn: "Masuaku", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 3.9 },
  { id: "epl-323", name: "캠벨", nameEn: "Campbell", team: "에버턴", teamEn: "Everton", position: "DF", cost: 3.9 },
  { id: "epl-324", name: "저스틴", nameEn: "Justin", team: "리즈", teamEn: "Leeds", position: "DF", cost: 3.9 },
  { id: "epl-325", name: "패터슨", nameEn: "Patterson", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 3.9 },
  { id: "epl-326", name: "음푸니", nameEn: "Mfuni", team: "맨시티", teamEn: "Man City", position: "DF", cost: 3.9 },
  { id: "epl-327", name: "클라크", nameEn: "Clarke", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 3.8 },
  { id: "epl-328", name: "소우사", nameEn: "Sousa", team: "아스톤 빌라", teamEn: "Aston Villa", position: "DF", cost: 3.8 },
  { id: "epl-329", name: "아킨보니", nameEn: "Akinmboni", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 3.8 },
  { id: "epl-330", name: "베번", nameEn: "Bevan", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 3.8 },
  { id: "epl-331", name: "아라우조", nameEn: "J.Araujo", team: "본머스", teamEn: "Bournemouth", position: "DF", cost: 3.8 },
  { id: "epl-332", name: "아서", nameEn: "Arthur", team: "브렌트퍼드", teamEn: "Brentford", position: "DF", cost: 3.8 },
  { id: "epl-333", name: "태스커", nameEn: "Tasker", team: "브라이턴", teamEn: "Brighton", position: "DF", cost: 3.8 },
  { id: "epl-334", name: "델크루아", nameEn: "Delcroix", team: "번리", teamEn: "Burnley", position: "DF", cost: 3.8 },
  { id: "epl-335", name: "루카스 피레스", nameEn: "Lucas Pires", team: "번리", teamEn: "Burnley", position: "DF", cost: 3.8 },
  { id: "epl-336", name: "소네", nameEn: "Sonne", team: "번리", teamEn: "Burnley", position: "DF", cost: 3.8 },
  { id: "epl-337", name: "워럴", nameEn: "Worrall", team: "번리", teamEn: "Burnley", position: "DF", cost: 3.8 },
  { id: "epl-338", name: "클라인", nameEn: "Clyne", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "DF", cost: 3.8 },
  { id: "epl-339", name: "딕슨", nameEn: "Dixon", team: "에버턴", teamEn: "Everton", position: "DF", cost: 3.8 },
  { id: "epl-340", name: "웰치", nameEn: "Welch", team: "에버턴", teamEn: "Everton", position: "DF", cost: 3.8 },
  { id: "epl-341", name: "아미사", nameEn: "Amissah", team: "풀럼", teamEn: "Fulham", position: "DF", cost: 3.8 },
  { id: "epl-342", name: "보르나우", nameEn: "Bornauw", team: "리즈", teamEn: "Leeds", position: "DF", cost: 3.8 },
  { id: "epl-343", name: "바이럼", nameEn: "Byram", team: "리즈", teamEn: "Leeds", position: "DF", cost: 3.8 },
  { id: "epl-344", name: "구드문드손", nameEn: "Gudmundsson", team: "리즈", teamEn: "Leeds", position: "DF", cost: 3.8 },
  { id: "epl-345", name: "램지", nameEn: "Ramsay", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 3.8 },
  { id: "epl-346", name: "프레드릭손", nameEn: "Fredricson", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 3.8 },
  { id: "epl-347", name: "말라시아", nameEn: "Malacia", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 3.8 },
  { id: "epl-348", name: "머피", nameEn: "A.Murphy", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 3.8 },
  { id: "epl-349", name: "피바스", nameEn: "Pivas", team: "뉴캐슬", teamEn: "Newcastle", position: "DF", cost: 3.8 },
  { id: "epl-350", name: "애보트", nameEn: "Abbott", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 3.8 },
  { id: "epl-351", name: "볼리", nameEn: "Boly", team: "노팅엄", teamEn: "Nott'm Forest", position: "DF", cost: 3.8 },
  { id: "epl-352", name: "앤더슨", nameEn: "Anderson", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 3.8 },
  { id: "epl-353", name: "존슨", nameEn: "Johnson", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 3.8 },
  { id: "epl-354", name: "헤이닐두", nameEn: "Reinildo", team: "선덜랜드", teamEn: "Sunderland", position: "DF", cost: 3.8 },
  { id: "epl-355", name: "후버", nameEn: "Hoever", team: "울버햄턴", teamEn: "Wolves", position: "DF", cost: 3.8 },
  { id: "epl-356", name: "니콜스", nameEn: "Nichols", team: "아스널", teamEn: "Arsenal", position: "DF", cost: 3.7 },
  { id: "epl-357", name: "아체암퐁", nameEn: "Acheampong", team: "첼시", teamEn: "Chelsea", position: "DF", cost: 3.7 },
  { id: "epl-358", name: "날로", nameEn: "Nallo", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 3.7 },
  { id: "epl-359", name: "윌리엄스", nameEn: "R.Williams", team: "리버풀", teamEn: "Liverpool", position: "DF", cost: 3.7 },
  { id: "epl-360", name: "헤이븐", nameEn: "Heaven", team: "맨유", teamEn: "Man Utd", position: "DF", cost: 3.7 },
  { id: "epl-361", name: "살라", nameEn: "M.Salah", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 14 },
  { id: "epl-362", name: "파머", nameEn: "Palmer", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 10.6 },
  { id: "epl-363", name: "브루노 페르난데스", nameEn: "B.Fernandes", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 10 },
  { id: "epl-364", name: "사카", nameEn: "Saka", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 9.8 },
  { id: "epl-365", name: "음베우모", nameEn: "Mbeumo", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 8.7 },
  { id: "epl-366", name: "손흥민", nameEn: "Son", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 8.5 },
  { id: "epl-367", name: "비르츠", nameEn: "Wirtz", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 8.3 },
  { id: "epl-368", name: "마르무쉬", nameEn: "Marmoush", team: "맨시티", teamEn: "Man City", position: "MF", cost: 8.3 },
  { id: "epl-369", name: "세메뇨", nameEn: "Semenyo", team: "맨시티", teamEn: "Man City", position: "MF", cost: 8.2 },
  { id: "epl-370", name: "포든", nameEn: "Foden", team: "맨시티", teamEn: "Man City", position: "MF", cost: 8.1 },
  { id: "epl-371", name: "루이스 디아스", nameEn: "Luis Díaz", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 8 },
  { id: "epl-372", name: "쿠냐", nameEn: "Cunha", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 8 },
  { id: "epl-373", name: "외데고르", nameEn: "Ødegaard", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 7.8 },
  { id: "epl-374", name: "로저스", nameEn: "Rogers", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 7.6 },
  { id: "epl-375", name: "라이스", nameEn: "Rice", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 7.5 },
  { id: "epl-376", name: "가크포", nameEn: "Gakpo", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 7.3 },
  { id: "epl-377", name: "깁스화이트", nameEn: "Gibbs-White", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 7.3 },
  { id: "epl-378", name: "에제", nameEn: "Eze", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 7.2 },
  { id: "epl-379", name: "고든", nameEn: "Gordon", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 7.2 },
  { id: "epl-380", name: "클라위버르트", nameEn: "Kluivert", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 7 },
  { id: "epl-381", name: "네투", nameEn: "Neto", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 7 },
  { id: "epl-382", name: "래시포드", nameEn: "Rashford", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 7 },
  { id: "epl-383", name: "샤데", nameEn: "Schade", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 6.9 },
  { id: "epl-384", name: "소보슬라이", nameEn: "Szoboszlai", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 6.9 },
  { id: "epl-385", name: "사비뉴", nameEn: "Savinho", team: "맨시티", teamEn: "Man City", position: "MF", cost: 6.9 },
  { id: "epl-386", name: "마두에케", nameEn: "Madueke", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 6.8 },
  { id: "epl-387", name: "마르티넬리", nameEn: "Martinelli", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 6.8 },
  { id: "epl-388", name: "브루노 기마랑이스", nameEn: "Bruno G.", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 6.8 },
  { id: "epl-389", name: "매디슨", nameEn: "Maddison", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 6.8 },
  { id: "epl-390", name: "트로사르", nameEn: "Trossard", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 6.7 },
  { id: "epl-391", name: "엔소", nameEn: "Enzo", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 6.7 },
  { id: "epl-392", name: "엘랑가", nameEn: "Elanga", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 6.5 },
  { id: "epl-393", name: "존슨", nameEn: "Johnson", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 6.5 },
  { id: "epl-394", name: "사비", nameEn: "Xavi", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 6.5 },
  { id: "epl-395", name: "에스테방", nameEn: "Estêvão", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 6.4 },
  { id: "epl-396", name: "이워비", nameEn: "Iwobi", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 6.4 },
  { id: "epl-397", name: "셰르키", nameEn: "Cherki", team: "맨시티", teamEn: "Man City", position: "MF", cost: 6.4 },
  { id: "epl-398", name: "도쿠", nameEn: "Doku", team: "맨시티", teamEn: "Man City", position: "MF", cost: 6.4 },
  { id: "epl-399", name: "가르나초", nameEn: "Garnacho", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 6.4 },
  { id: "epl-400", name: "쿠두스", nameEn: "Kudus", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 6.4 },
  { id: "epl-401", name: "쿨루세프스키", nameEn: "Kulusevski", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 6.4 },
  { id: "epl-402", name: "사르", nameEn: "Sarr", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 6.3 },
  { id: "epl-403", name: "키에사", nameEn: "Chiesa", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 6.3 },
  { id: "epl-404", name: "그릴리쉬", nameEn: "Grealish", team: "에버턴", teamEn: "Everton", position: "MF", cost: 6.3 },
  { id: "epl-405", name: "귄도안", nameEn: "Gündoğan", team: "맨시티", teamEn: "Man City", position: "MF", cost: 6.3 },
  { id: "epl-406", name: "로드리고", nameEn: "Rodrigo", team: "맨시티", teamEn: "Man City", position: "MF", cost: 6.3 },
  { id: "epl-407", name: "은디아예", nameEn: "Ndiaye", team: "에버턴", teamEn: "Everton", position: "MF", cost: 6.2 },
  { id: "epl-408", name: "맥 알리스터", nameEn: "Mac Allister", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 6.2 },
  { id: "epl-409", name: "베르나르두", nameEn: "Bernardo", team: "맨시티", teamEn: "Man City", position: "MF", cost: 6.2 },
  { id: "epl-410", name: "아마드", nameEn: "Amad", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 6.2 },
  { id: "epl-411", name: "텔", nameEn: "Tel", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 6.2 },
  { id: "epl-412", name: "게상", nameEn: "Guessand", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 6.2 },
  { id: "epl-413", name: "미토마", nameEn: "Mitoma", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 6.1 },
  { id: "epl-414", name: "반스", nameEn: "Barnes", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 6.1 },
  { id: "epl-415", name: "당고", nameEn: "O.Dango", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 6 },
  { id: "epl-416", name: "기텐스", nameEn: "Gittens", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 6 },
  { id: "epl-417", name: "윌슨", nameEn: "Wilson", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 6 },
  { id: "epl-418", name: "틸레만스", nameEn: "Tielemans", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5.9 },
  { id: "epl-419", name: "은쿤쿠", nameEn: "Nkunku", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 5.9 },
  { id: "epl-420", name: "곤살레스", nameEn: "N.Gonzalez", team: "맨시티", teamEn: "Man City", position: "MF", cost: 5.9 },
  { id: "epl-421", name: "안토니", nameEn: "Antony", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 5.9 },
  { id: "epl-422", name: "마운트", nameEn: "Mount", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 5.9 },
  { id: "epl-423", name: "머피", nameEn: "J.Murphy", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 5.9 },
  { id: "epl-424", name: "조엘링턴", nameEn: "Joelinton", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 5.9 },
  { id: "epl-425", name: "파게타", nameEn: "L.Paquetá", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 5.9 },
  { id: "epl-426", name: "바크와", nameEn: "Bakwa", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 5.9 },
  { id: "epl-427", name: "마치", nameEn: "March", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 5.8 },
  { id: "epl-428", name: "코바치치", nameEn: "Kovačić", team: "맨시티", teamEn: "Man City", position: "MF", cost: 5.8 },
  { id: "epl-429", name: "산초", nameEn: "Sancho", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5.8 },
  { id: "epl-430", name: "예레미", nameEn: "Yeremy", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 5.8 },
  { id: "epl-431", name: "케빈", nameEn: "Kevin", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 5.8 },
  { id: "epl-432", name: "카이세도", nameEn: "Caicedo", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 5.7 },
  { id: "epl-433", name: "허드슨오도이", nameEn: "Hudson-Odoi", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 5.7 },
  { id: "epl-434", name: "소우체크", nameEn: "Souček", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 5.7 },
  { id: "epl-435", name: "서머빌", nameEn: "Summerville", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 5.7 },
  { id: "epl-436", name: "담스고르", nameEn: "Damsgaard", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 5.6 },
  { id: "epl-437", name: "조르지뉴", nameEn: "Georginio", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 5.6 },
  { id: "epl-438", name: "스미스 로우", nameEn: "Smith Rowe", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 5.6 },
  { id: "epl-439", name: "카세미루", nameEn: "Casemiro", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 5.6 },
  { id: "epl-440", name: "워드프라우스", nameEn: "Ward-Prowse", team: "번리", teamEn: "Burnley", position: "MF", cost: 5.6 },
  { id: "epl-441", name: "황희찬", nameEn: "Hee Chan", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 5.6 },
  { id: "epl-442", name: "라이안", nameEn: "Rayan", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 5.6 },
  { id: "epl-443", name: "베일리", nameEn: "Bailey", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5.5 },
  { id: "epl-444", name: "일링 주니어", nameEn: "Iling Jr", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5.5 },
  { id: "epl-445", name: "민테", nameEn: "Minteh", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 5.5 },
  { id: "epl-446", name: "오라일리", nameEn: "O'Riley", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 5.5 },
  { id: "epl-447", name: "맥닐", nameEn: "McNeil", team: "에버턴", teamEn: "Everton", position: "MF", cost: 5.5 },
  { id: "epl-448", name: "흐라벤베르흐", nameEn: "Gravenberch", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 5.5 },
  { id: "epl-449", name: "게데스", nameEn: "Guedes", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 5.5 },
  { id: "epl-450", name: "은도예", nameEn: "Ndoye", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 5.5 },
  { id: "epl-451", name: "팔리냐", nameEn: "J.Palhinha", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 5.5 },
  { id: "epl-452", name: "오카포르", nameEn: "Okafor", team: "리즈", teamEn: "Leeds", position: "MF", cost: 5.5 },
  { id: "epl-453", name: "페르난데스", nameEn: "M.Fernandes", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 5.5 },
  { id: "epl-454", name: "트라오레", nameEn: "Traoré", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 5.5 },
  { id: "epl-455", name: "그로스", nameEn: "Groß", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 5.5 },
  { id: "epl-456", name: "메리노", nameEn: "Merino", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 5.4 },
  { id: "epl-457", name: "파비우 비에이라", nameEn: "Fábio Vieira", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 5.4 },
  { id: "epl-458", name: "맥긴", nameEn: "McGinn", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5.4 },
  { id: "epl-459", name: "엔시소", nameEn: "Enciso", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 5.4 },
  { id: "epl-460", name: "그루다", nameEn: "Gruda", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 5.4 },
  { id: "epl-461", name: "시마", nameEn: "Sima", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 5.4 },
  { id: "epl-462", name: "벤슨", nameEn: "Benson", team: "번리", teamEn: "Burnley", position: "MF", cost: 5.4 },
  { id: "epl-463", name: "게예", nameEn: "Gana", team: "에버턴", teamEn: "Everton", position: "MF", cost: 5.4 },
  { id: "epl-464", name: "세세뇽", nameEn: "Sessegnon", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 5.4 },
  { id: "epl-465", name: "에런슨", nameEn: "Aaronson", team: "리즈", teamEn: "Leeds", position: "MF", cost: 5.4 },
  { id: "epl-466", name: "존스", nameEn: "C.Jones", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 5.4 },
  { id: "epl-467", name: "에체베리", nameEn: "Echeverri", team: "맨시티", teamEn: "Man City", position: "MF", cost: 5.4 },
  { id: "epl-468", name: "앤더슨", nameEn: "Anderson", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 5.4 },
  { id: "epl-469", name: "조타", nameEn: "Jota", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 5.4 },
  { id: "epl-470", name: "로버츠", nameEn: "Roberts", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 5.4 },
  { id: "epl-471", name: "솔로몬", nameEn: "Solomon", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 5.4 },
  { id: "epl-472", name: "허친슨", nameEn: "Hutchinson", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 5.4 },
  { id: "epl-473", name: "아들리", nameEn: "Adli", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 5.4 },
  { id: "epl-474", name: "부엔디아", nameEn: "Buendía", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5.3 },
  { id: "epl-475", name: "램지", nameEn: "J.Ramsey", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 5.3 },
  { id: "epl-476", name: "태버니어", nameEn: "Tavernier", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 5.3 },
  { id: "epl-477", name: "브룬 라르센", nameEn: "Bruun Larsen", team: "번리", teamEn: "Burnley", position: "MF", cost: 5.3 },
  { id: "epl-478", name: "안드레아스", nameEn: "Andreas", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 5.3 },
  { id: "epl-479", name: "토날리", nameEn: "Tonali", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 5.3 },
  { id: "epl-480", name: "디아라", nameEn: "Diarra", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 5.3 },
  { id: "epl-481", name: "오도베르", nameEn: "Odobert", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 5.3 },
  { id: "epl-482", name: "고메스", nameEn: "J.Gomes", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 5.3 },
  { id: "epl-483", name: "무네치", nameEn: "Munetsi", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 5.3 },
  { id: "epl-484", name: "디블링", nameEn: "Dibling", team: "에버턴", teamEn: "Everton", position: "MF", cost: 5.3 },
  { id: "epl-485", name: "추크우에제", nameEn: "Chukwueze", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 5.3 },
  { id: "epl-486", name: "갤러거", nameEn: "Gallagher", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 5.3 },
  { id: "epl-487", name: "수비멘디", nameEn: "Zubimendi", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 5.2 },
  { id: "epl-488", name: "밀람보", nameEn: "Milambo", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 5.2 },
  { id: "epl-489", name: "알카라스", nameEn: "Alcaraz", team: "에버턴", teamEn: "Everton", position: "MF", cost: 5.2 },
  { id: "epl-490", name: "가너", nameEn: "Garner", team: "에버턴", teamEn: "Everton", position: "MF", cost: 5.2 },
  { id: "epl-491", name: "뇬토", nameEn: "Gnonto", team: "리즈", teamEn: "Leeds", position: "MF", cost: 5.2 },
  { id: "epl-492", name: "제임스", nameEn: "James", team: "리즈", teamEn: "Leeds", position: "MF", cost: 5.2 },
  { id: "epl-493", name: "벤탄쿠르", nameEn: "Bentancur", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 5.2 },
  { id: "epl-494", name: "베리발", nameEn: "Bergvall", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 5.2 },
  { id: "epl-495", name: "비수마", nameEn: "Bissouma", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 5.2 },
  { id: "epl-496", name: "안드레", nameEn: "André", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 5.2 },
  { id: "epl-497", name: "뇌르고르", nameEn: "Nørgaard", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 5.1 },
  { id: "epl-498", name: "말렌", nameEn: "Malen", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5.1 },
  { id: "epl-499", name: "스콧", nameEn: "Scott", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 5.1 },
  { id: "epl-500", name: "힌셸우드", nameEn: "Hinshelwood", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 5.1 },
  { id: "epl-501", name: "듀스버리홀", nameEn: "Dewsbury-Hall", team: "에버턴", teamEn: "Everton", position: "MF", cost: 5.1 },
  { id: "epl-502", name: "아다마", nameEn: "Adama", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 5.1 },
  { id: "epl-503", name: "해리슨", nameEn: "Harrison", team: "리즈", teamEn: "Leeds", position: "MF", cost: 5.1 },
  { id: "epl-504", name: "엘리엇", nameEn: "Elliott", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5.1 },
  { id: "epl-505", name: "봅", nameEn: "Bobb", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 5.1 },
  { id: "epl-506", name: "벨가르드", nameEn: "Bellegarde", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 5.1 },
  { id: "epl-507", name: "페르 로페스", nameEn: "Fer López", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 5.1 },
  { id: "epl-508", name: "자카", nameEn: "Xhaka", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 5.1 },
  { id: "epl-509", name: "은와네리", nameEn: "Nwaneri", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 5 },
  { id: "epl-510", name: "바레네체아", nameEn: "Barrenechea", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5 },
  { id: "epl-511", name: "도빈", nameEn: "Dobbin", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5 },
  { id: "epl-512", name: "브룩스", nameEn: "Brooks", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 5 },
  { id: "epl-513", name: "시니스테라", nameEn: "Sinisterra", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 5 },
  { id: "epl-514", name: "헨더슨", nameEn: "Henderson", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 5 },
  { id: "epl-515", name: "야르몰류크", nameEn: "Yarmoliuk", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 5 },
  { id: "epl-516", name: "얄쿠예", nameEn: "Yalcouye", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 5 },
  { id: "epl-517", name: "앤서니", nameEn: "Anthony", team: "번리", teamEn: "Burnley", position: "MF", cost: 5 },
  { id: "epl-518", name: "콜레오쇼", nameEn: "Koleosho", team: "번리", teamEn: "Burnley", position: "MF", cost: 5 },
  { id: "epl-519", name: "카마다", nameEn: "Kamada", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 5 },
  { id: "epl-520", name: "와튼", nameEn: "Wharton", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 5 },
  { id: "epl-521", name: "맥아티", nameEn: "McAtee", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 5 },
  { id: "epl-522", name: "레인더르스", nameEn: "Reijnders", team: "맨시티", teamEn: "Man City", position: "MF", cost: 5 },
  { id: "epl-523", name: "뉘판", nameEn: "Nypan", team: "맨시티", teamEn: "Man City", position: "MF", cost: 5 },
  { id: "epl-524", name: "윌록", nameEn: "Willock", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 5 },
  { id: "epl-525", name: "도밍게스", nameEn: "Dominguez", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 5 },
  { id: "epl-526", name: "오브라이언", nameEn: "O'Brien", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 5 },
  { id: "epl-527", name: "르 페", nameEn: "E.Le Fée", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 5 },
  { id: "epl-528", name: "무어", nameEn: "Moore", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 5 },
  { id: "epl-529", name: "트라오레", nameEn: "B.Traore", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 5 },
  { id: "epl-530", name: "우고추쿠", nameEn: "Ugochukwu", team: "번리", teamEn: "Burnley", position: "MF", cost: 5 },
  { id: "epl-531", name: "마가사", nameEn: "S.Magassa", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 5 },
  { id: "epl-532", name: "플로렌티누", nameEn: "Florentino", team: "번리", teamEn: "Burnley", position: "MF", cost: 5 },
  { id: "epl-533", name: "뢸", nameEn: "Röhl", team: "에버턴", teamEn: "Everton", position: "MF", cost: 5 },
  { id: "epl-534", name: "알리송", nameEn: "Alysson", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 5 },
  { id: "epl-535", name: "조슬린", nameEn: "Jocelin.T", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 5 },
  { id: "epl-536", name: "토트", nameEn: "Tóth.A", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 5 },
  { id: "epl-537", name: "라마드리드", nameEn: "Lamadrid", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 5 },
  { id: "epl-538", name: "앙굴로", nameEn: "Angulo", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 5 },
  { id: "epl-539", name: "카마라", nameEn: "Kamara", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 4.9 },
  { id: "epl-540", name: "아담스", nameEn: "Adams", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.9 },
  { id: "epl-541", name: "크리스티", nameEn: "Christie", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.9 },
  { id: "epl-542", name: "쿡", nameEn: "Cook", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.9 },
  { id: "epl-543", name: "필립", nameEn: "Philip", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.9 },
  { id: "epl-544", name: "야넬트", nameEn: "Janelt", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.9 },
  { id: "epl-545", name: "옌센", nameEn: "Jensen", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.9 },
  { id: "epl-546", name: "누네스", nameEn: "Nunes", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.9 },
  { id: "epl-547", name: "고메스", nameEn: "Gomez", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.9 },
  { id: "epl-548", name: "밀너", nameEn: "Milner", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.9 },
  { id: "epl-549", name: "사르미엔토", nameEn: "Sarmiento", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.9 },
  { id: "epl-550", name: "비퍼", nameEn: "Wieffer", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.9 },
  { id: "epl-551", name: "추를리노프", nameEn: "Churlinov", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.9 },
  { id: "epl-552", name: "컬런", nameEn: "Cullen", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.9 },
  { id: "epl-553", name: "차우나", nameEn: "Tchaouna", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.9 },
  { id: "epl-554", name: "라비아", nameEn: "Lavia", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 4.9 },
  { id: "epl-555", name: "무드리크", nameEn: "Mudryk", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 4.9 },
  { id: "epl-556", name: "두쿠레", nameEn: "Doucouré", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.9 },
  { id: "epl-557", name: "레르마", nameEn: "Lerma", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.9 },
  { id: "epl-558", name: "베르게", nameEn: "Berge", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 4.9 },
  { id: "epl-559", name: "루키치", nameEn: "Lukić", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 4.9 },
  { id: "epl-560", name: "암파두", nameEn: "Ampadu", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.9 },
  { id: "epl-561", name: "그린우드", nameEn: "Greenwood", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.9 },
  { id: "epl-562", name: "라마자니", nameEn: "Ramazani", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.9 },
  { id: "epl-563", name: "엔도", nameEn: "Endo", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 4.9 },
  { id: "epl-564", name: "안토니토", nameEn: "Antoñito C.", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 4.9 },
  { id: "epl-565", name: "상가레", nameEn: "Sangaré", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 4.9 },
  { id: "epl-566", name: "아딩그라", nameEn: "Adingra", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.9 },
  { id: "epl-567", name: "알렉시치", nameEn: "Aleksić", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.9 },
  { id: "epl-568", name: "먼들", nameEn: "Mundle", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.9 },
  { id: "epl-569", name: "사디키", nameEn: "Sadiki", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.9 },
  { id: "epl-570", name: "탈비", nameEn: "Talbi", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.9 },
  { id: "epl-571", name: "브라이언", nameEn: "Bryan", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 4.9 },
  { id: "epl-572", name: "알바레스", nameEn: "Álvarez", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 4.9 },
  { id: "epl-573", name: "코르네", nameEn: "Cornet", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 4.9 },
  { id: "epl-574", name: "길레르미", nameEn: "L.Guilherme", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 4.9 },
  { id: "epl-575", name: "아리아스", nameEn: "J.Arias", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 4.9 },
  { id: "epl-576", name: "더글라스 루이스", nameEn: "Douglas Luiz", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 4.9 },
  { id: "epl-577", name: "다실바", nameEn: "Dasilva", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.9 },
  { id: "epl-578", name: "넬슨", nameEn: "Nelson", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.8 },
  { id: "epl-579", name: "바클리", nameEn: "Barkley", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 4.8 },
  { id: "epl-580", name: "오나나", nameEn: "Onana", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 4.8 },
  { id: "epl-581", name: "오녜카", nameEn: "Onyeka", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.8 },
  { id: "epl-582", name: "아야리", nameEn: "Ayari", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.8 },
  { id: "epl-583", name: "왓슨", nameEn: "Watson", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.8 },
  { id: "epl-584", name: "로랑", nameEn: "Laurent", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.8 },
  { id: "epl-585", name: "조지", nameEn: "George", team: "에버턴", teamEn: "Everton", position: "MF", cost: 4.8 },
  { id: "epl-586", name: "이로에그부남", nameEn: "Iroegbunam", team: "에버턴", teamEn: "Everton", position: "MF", cost: 4.8 },
  { id: "epl-587", name: "케어니", nameEn: "Cairney", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 4.8 },
  { id: "epl-588", name: "다나카", nameEn: "Tanaka", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.8 },
  { id: "epl-589", name: "개넌도크", nameEn: "Gannon-Doak", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.8 },
  { id: "epl-590", name: "롱스태프", nameEn: "Longstaff", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.8 },
  { id: "epl-591", name: "닐", nameEn: "Neil", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.8 },
  { id: "epl-592", name: "포베다", nameEn: "Poveda", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.8 },
  { id: "epl-593", name: "그레이", nameEn: "Gray", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 4.8 },
  { id: "epl-594", name: "로드리게스", nameEn: "G.Rodriguez", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 4.8 },
  { id: "epl-595", name: "앙헬", nameEn: "Angel", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 4.8 },
  { id: "epl-596", name: "카르발류", nameEn: "Carvalho", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.7 },
  { id: "epl-597", name: "보아텡", nameEn: "Boateng", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.7 },
  { id: "epl-598", name: "에드워즈", nameEn: "Edwards", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.7 },
  { id: "epl-599", name: "한니발", nameEn: "Hannibal", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.7 },
  { id: "epl-600", name: "에세", nameEn: "Esse", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.7 },
  { id: "epl-601", name: "휴즈", nameEn: "Hughes", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.7 },
  { id: "epl-602", name: "그루에프", nameEn: "Gruev", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.7 },
  { id: "epl-603", name: "필립스", nameEn: "Phillips", team: "맨시티", teamEn: "Man City", position: "MF", cost: 4.7 },
  { id: "epl-604", name: "우가르테", nameEn: "Ugarte", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 4.7 },
  { id: "epl-605", name: "예이츠", nameEn: "Yates", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 4.7 },
  { id: "epl-606", name: "리그", nameEn: "Rigg", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.7 },
  { id: "epl-607", name: "스타흐", nameEn: "Stach", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.7 },
  { id: "epl-608", name: "부오나노테", nameEn: "Buonanotte", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.6 },
  { id: "epl-609", name: "마이누", nameEn: "Mainoo", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 4.6 },
  { id: "epl-610", name: "카비아", nameEn: "Kabia", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 4.5 },
  { id: "epl-611", name: "삼비", nameEn: "Sambi", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 4.5 },
  { id: "epl-612", name: "덴동커", nameEn: "Dendoncker", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 4.5 },
  { id: "epl-613", name: "지모알로바", nameEn: "Jimoh-Aloba", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 4.5 },
  { id: "epl-614", name: "페브르", nameEn: "Faivre", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.5 },
  { id: "epl-615", name: "트라오레", nameEn: "H.Traorè", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.5 },
  { id: "epl-616", name: "사디", nameEn: "Sadi", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.5 },
  { id: "epl-617", name: "윈터번", nameEn: "Winterburn", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.5 },
  { id: "epl-618", name: "마고마", nameEn: "Maghoma", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.5 },
  { id: "epl-619", name: "트레빗", nameEn: "Trevitt", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.5 },
  { id: "epl-620", name: "발레바", nameEn: "Baleba", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.5 },
  { id: "epl-621", name: "마질루", nameEn: "Mazilu", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.5 },
  { id: "epl-622", name: "모란", nameEn: "Moran", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.5 },
  { id: "epl-623", name: "아데우미", nameEn: "Adewumi", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.5 },
  { id: "epl-624", name: "바넬", nameEn: "Banel", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.5 },
  { id: "epl-625", name: "안드레이 산투스", nameEn: "Andrey Santos", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 4.5 },
  { id: "epl-626", name: "파에스", nameEn: "Paez", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 4.5 },
  { id: "epl-627", name: "에비오웨이", nameEn: "Ebiowei", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.5 },
  { id: "epl-628", name: "프랑사", nameEn: "M.França", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.5 },
  { id: "epl-629", name: "오조", nameEn: "Ozoh", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.5 },
  { id: "epl-630", name: "우메", nameEn: "Umeh", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.5 },
  { id: "epl-631", name: "암스트롱", nameEn: "Armstrong", team: "에버턴", teamEn: "Everton", position: "MF", cost: 4.5 },
  { id: "epl-632", name: "히스", nameEn: "Heath", team: "에버턴", teamEn: "Everton", position: "MF", cost: 4.5 },
  { id: "epl-633", name: "멧칼프", nameEn: "Metcalfe", team: "에버턴", teamEn: "Everton", position: "MF", cost: 4.5 },
  { id: "epl-634", name: "고도", nameEn: "Godo", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 4.5 },
  { id: "epl-635", name: "해리스", nameEn: "Harris", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 4.5 },
  { id: "epl-636", name: "크루", nameEn: "Crew", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.5 },
  { id: "epl-637", name: "겔하르트", nameEn: "Gelhardt", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.5 },
  { id: "epl-638", name: "자비", nameEn: "Gyabi", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.5 },
  { id: "epl-639", name: "모턴", nameEn: "Morton", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 4.5 },
  { id: "epl-640", name: "콜리어", nameEn: "Collyer", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 4.5 },
  { id: "epl-641", name: "무어하우스", nameEn: "Moorhouse", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 4.5 },
  { id: "epl-642", name: "헤이든", nameEn: "Hayden", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 4.5 },
  { id: "epl-643", name: "화이트", nameEn: "White", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 4.5 },
  { id: "epl-644", name: "다실바 모레이라", nameEn: "Da Silva Moreira", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 4.5 },
  { id: "epl-645", name: "스타메니치", nameEn: "Stamenic", team: "노팅엄", teamEn: "Nott'm Forest", position: "MF", cost: 4.5 },
  { id: "epl-646", name: "브라운", nameEn: "Browne", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.5 },
  { id: "epl-647", name: "에콰", nameEn: "Ekwah", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.5 },
  { id: "epl-648", name: "사르", nameEn: "P.M.Sarr", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 4.5 },
  { id: "epl-649", name: "민혁", nameEn: "Min-hyeok", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 4.5 },
  { id: "epl-650", name: "어시", nameEn: "Earthy", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 4.5 },
  { id: "epl-651", name: "호지", nameEn: "Hodge", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 4.5 },
  { id: "epl-652", name: "오냥고", nameEn: "Onyango", team: "에버턴", teamEn: "Everton", position: "MF", cost: 4.5 },
  { id: "epl-653", name: "맥에이두", nameEn: "McAidoo", team: "맨시티", teamEn: "Man City", position: "MF", cost: 4.5 },
  { id: "epl-654", name: "에메날로", nameEn: "Emenalo", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 4.5 },
  { id: "epl-655", name: "오리올라", nameEn: "Oriola", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.5 },
  { id: "epl-656", name: "모리슨", nameEn: "Morrison", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 4.5 },
  { id: "epl-657", name: "아캄리치", nameEn: "Akhamrich", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 4.5 },
  { id: "epl-658", name: "조지 헤밍스", nameEn: "George Hemmings", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 4.5 },
  { id: "epl-659", name: "레이시", nameEn: "Lacey", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 4.5 },
  { id: "epl-660", name: "다코스타", nameEn: "DaCosta", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.5 },
  { id: "epl-661", name: "칸테", nameEn: "Mohamadou Kanté", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 4.5 },
  { id: "epl-662", name: "드레이크스토마스", nameEn: "Drakes-Thomas", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.5 },
  { id: "epl-663", name: "그레이", nameEn: "Gray", team: "맨시티", teamEn: "Man City", position: "MF", cost: 4.5 },
  { id: "epl-664", name: "헤스키", nameEn: "Heskey", team: "맨시티", teamEn: "Man City", position: "MF", cost: 4.5 },
  { id: "epl-665", name: "롤링스", nameEn: "Rawlings", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 4.5 },
  { id: "epl-666", name: "벤디토 만타토", nameEn: "Bendito Mantato", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 4.5 },
  { id: "epl-667", name: "리전", nameEn: "Ridgeon", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 4.5 },
  { id: "epl-668", name: "알라비", nameEn: "Alabi", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 4.5 },
  { id: "epl-669", name: "투티에로프", nameEn: "Tutierov", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.5 },
  { id: "epl-670", name: "핌롯", nameEn: "Pimlott", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.5 },
  { id: "epl-671", name: "오진나카", nameEn: "Ojinnaka", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 4.5 },
  { id: "epl-672", name: "서덜랜드", nameEn: "Sutherland", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 4.5 },
  { id: "epl-673", name: "브라이얼리", nameEn: "Brierley", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.5 },
  { id: "epl-674", name: "윌리엄스바넷", nameEn: "Williams-Barnett", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 4.5 },
  { id: "epl-675", name: "하웰", nameEn: "Howell", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.5 },
  { id: "epl-676", name: "스티븐스", nameEn: "Stevens", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.5 },
  { id: "epl-677", name: "애비", nameEn: "Abbey", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 4.5 },
  { id: "epl-678", name: "벤트", nameEn: "Bentt", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.5 },
  { id: "epl-679", name: "키에레마텐", nameEn: "Kyerematen", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 4.5 },
  { id: "epl-680", name: "맥마흔브라운", nameEn: "McMahon-Brown", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.5 },
  { id: "epl-681", name: "브로지오", nameEn: "Broggio", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 4.4 },
  { id: "epl-682", name: "실콧더베리", nameEn: "Silcott-Duberry", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.4 },
  { id: "epl-683", name: "도너번", nameEn: "Donovan", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.4 },
  { id: "epl-684", name: "피어트해리스", nameEn: "Peart-Harris", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.4 },
  { id: "epl-685", name: "나이트", nameEn: "Knight", team: "브라이턴", teamEn: "Brighton", position: "MF", cost: 4.4 },
  { id: "epl-686", name: "램지", nameEn: "A.Ramsey", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.4 },
  { id: "epl-687", name: "트레소르", nameEn: "Trésor", team: "번리", teamEn: "Burnley", position: "MF", cost: 4.4 },
  { id: "epl-688", name: "락사키", nameEn: "J.Rak-Sakyi", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.4 },
  { id: "epl-689", name: "로드니", nameEn: "Rodney", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.4 },
  { id: "epl-690", name: "에베레", nameEn: "Ebere", team: "에버턴", teamEn: "Everton", position: "MF", cost: 4.4 },
  { id: "epl-691", name: "킹", nameEn: "King", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 4.4 },
  { id: "epl-692", name: "맥코널", nameEn: "McConnell", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 4.4 },
  { id: "epl-693", name: "쿠올", nameEn: "Kuol", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 4.4 },
  { id: "epl-694", name: "마일리", nameEn: "L.Miley", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 4.4 },
  { id: "epl-695", name: "트리안티스", nameEn: "Triantis", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.4 },
  { id: "epl-696", name: "오포드", nameEn: "Orford", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 4.4 },
  { id: "epl-697", name: "팟츠", nameEn: "Potts", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 4.4 },
  { id: "epl-698", name: "카르디네스", nameEn: "Cardines", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.4 },
  { id: "epl-699", name: "버로스", nameEn: "Burrowes", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 4.4 },
  { id: "epl-700", name: "해리먼아누스", nameEn: "Harriman-Annous", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 4.4 },
  { id: "epl-701", name: "무카사", nameEn: "Mukasa", team: "맨시티", teamEn: "Man City", position: "MF", cost: 4.4 },
  { id: "epl-702", name: "플레처", nameEn: "Fletcher", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 4.4 },
  { id: "epl-703", name: "체임버스", nameEn: "Chambers", team: "리즈", teamEn: "Leeds", position: "MF", cost: 4.4 },
  { id: "epl-704", name: "영", nameEn: "Young", team: "아스톤 빌라", teamEn: "Aston Villa", position: "MF", cost: 4.3 },
  { id: "epl-705", name: "코나크", nameEn: "Konak", team: "브렌트퍼드", teamEn: "Brentford", position: "MF", cost: 4.3 },
  { id: "epl-706", name: "에수고", nameEn: "D.Essugo", team: "첼시", teamEn: "Chelsea", position: "MF", cost: 4.3 },
  { id: "epl-707", name: "아그비노네", nameEn: "Agbinone", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.3 },
  { id: "epl-708", name: "아하마다", nameEn: "Ahamada", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.3 },
  { id: "epl-709", name: "데베니", nameEn: "Devenny", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "MF", cost: 4.3 },
  { id: "epl-710", name: "베이츠", nameEn: "Bates", team: "에버턴", teamEn: "Everton", position: "MF", cost: 4.3 },
  { id: "epl-711", name: "리드", nameEn: "Reed", team: "풀럼", teamEn: "Fulham", position: "MF", cost: 4.3 },
  { id: "epl-712", name: "뇨니", nameEn: "Nyoni", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 4.3 },
  { id: "epl-713", name: "피츠제럴드", nameEn: "Fitzgerald", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 4.3 },
  { id: "epl-714", name: "플레처", nameEn: "J.Fletcher", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 4.3 },
  { id: "epl-715", name: "코네", nameEn: "Kone", team: "맨유", teamEn: "Man Utd", position: "MF", cost: 4.3 },
  { id: "epl-716", name: "바", nameEn: "Ba", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.3 },
  { id: "epl-717", name: "존스", nameEn: "H.Jones", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.3 },
  { id: "epl-718", name: "마테테", nameEn: "Matete", team: "선덜랜드", teamEn: "Sunderland", position: "MF", cost: 4.3 },
  { id: "epl-719", name: "올루세시", nameEn: "Olusesi", team: "토트넘", teamEn: "Spurs", position: "MF", cost: 4.3 },
  { id: "epl-720", name: "어빙", nameEn: "Irving", team: "웨스트햄", teamEn: "West Ham", position: "MF", cost: 4.3 },
  { id: "epl-721", name: "치레와", nameEn: "Chirewa", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 4.3 },
  { id: "epl-722", name: "에도지", nameEn: "Edozie", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 4.3 },
  { id: "epl-723", name: "곤살레스", nameEn: "Gonzalez", team: "울버햄턴", teamEn: "Wolves", position: "MF", cost: 4.3 },
  { id: "epl-724", name: "응구모하", nameEn: "Ngumoha", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 4.3 },
  { id: "epl-725", name: "리스도틴", nameEn: "Rees-Dottin", team: "본머스", teamEn: "Bournemouth", position: "MF", cost: 4.3 },
  { id: "epl-726", name: "승수", nameEn: "Seung soo", team: "뉴캐슬", teamEn: "Newcastle", position: "MF", cost: 4.3 },
  { id: "epl-727", name: "바이체티치", nameEn: "Bajcetic", team: "리버풀", teamEn: "Liverpool", position: "MF", cost: 4.2 },
  { id: "epl-728", name: "다우만", nameEn: "Dowman", team: "아스널", teamEn: "Arsenal", position: "MF", cost: 4.2 },
  { id: "epl-729", name: "홀란드", nameEn: "Haaland", team: "맨시티", teamEn: "Man City", position: "FW", cost: 14.7 },
  { id: "epl-730", name: "이삭", nameEn: "Isak", team: "리버풀", teamEn: "Liverpool", position: "FW", cost: 10.3 },
  { id: "epl-731", name: "에키티케", nameEn: "Ekitiké", team: "리버풀", teamEn: "Liverpool", position: "FW", cost: 9.1 },
  { id: "epl-732", name: "요케레스", nameEn: "Gyökeres", team: "아스널", teamEn: "Arsenal", position: "FW", cost: 8.8 },
  { id: "epl-733", name: "왓킨스", nameEn: "Watkins", team: "아스톤 빌라", teamEn: "Aston Villa", position: "FW", cost: 8.5 },
  { id: "epl-734", name: "주앙 페드루", nameEn: "João Pedro", team: "첼시", teamEn: "Chelsea", position: "FW", cost: 7.6 },
  { id: "epl-735", name: "마테타", nameEn: "Mateta", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "FW", cost: 7.5 },
  { id: "epl-736", name: "보웬", nameEn: "Bowen", team: "웨스트햄", teamEn: "West Ham", position: "FW", cost: 7.5 },
  { id: "epl-737", name: "하베르츠", nameEn: "Havertz", team: "아스널", teamEn: "Arsenal", position: "FW", cost: 7.3 },
  { id: "epl-738", name: "비사", nameEn: "Wissa", team: "뉴캐슬", teamEn: "Newcastle", position: "FW", cost: 7.3 },
  { id: "epl-739", name: "셰슈코", nameEn: "Šeško", team: "맨유", teamEn: "Man Utd", position: "FW", cost: 7.3 },
  { id: "epl-740", name: "치아구", nameEn: "Thiago", team: "브렌트퍼드", teamEn: "Brentford", position: "FW", cost: 7.2 },
  { id: "epl-741", name: "우드", nameEn: "Wood", team: "노팅엄", teamEn: "Nott'm Forest", position: "FW", cost: 7.2 },
  { id: "epl-742", name: "솔란케", nameEn: "Solanke", team: "토트넘", teamEn: "Spurs", position: "FW", cost: 7.2 },
  { id: "epl-743", name: "콜로 무아니", nameEn: "Kolo Muani", team: "토트넘", teamEn: "Spurs", position: "FW", cost: 6.9 },
  { id: "epl-744", name: "에바닐송", nameEn: "Evanilson", team: "본머스", teamEn: "Bournemouth", position: "FW", cost: 6.8 },
  { id: "epl-745", name: "볼테마데", nameEn: "Woltemade", team: "뉴캐슬", teamEn: "Newcastle", position: "FW", cost: 6.8 },
  { id: "epl-746", name: "잭슨", nameEn: "N.Jackson", team: "첼시", teamEn: "Chelsea", position: "FW", cost: 6.5 },
  { id: "epl-747", name: "다윈", nameEn: "Darwin", team: "리버풀", teamEn: "Liverpool", position: "FW", cost: 6.5 },
  { id: "epl-748", name: "제주스", nameEn: "G.Jesus", team: "아스널", teamEn: "Arsenal", position: "FW", cost: 6.4 },
  { id: "epl-749", name: "회일룬", nameEn: "Højlund", team: "맨유", teamEn: "Man Utd", position: "FW", cost: 6.3 },
  { id: "epl-750", name: "히샬리송", nameEn: "Richarlison", team: "토트넘", teamEn: "Spurs", position: "FW", cost: 6.3 },
  { id: "epl-751", name: "딜랩", nameEn: "Delap", team: "첼시", teamEn: "Chelsea", position: "FW", cost: 6.2 },
  { id: "epl-752", name: "라울", nameEn: "Raúl", team: "풀럼", teamEn: "Fulham", position: "FW", cost: 6.2 },
  { id: "epl-753", name: "웰벡", nameEn: "Welbeck", team: "브라이턴", teamEn: "Brighton", position: "FW", cost: 6.1 },
  { id: "epl-754", name: "스트란 라르센", nameEn: "Strand Larsen", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "FW", cost: 6.1 },
  { id: "epl-755", name: "칼리무엔도", nameEn: "Kalimuendo", team: "노팅엄", teamEn: "Nott'm Forest", position: "FW", cost: 6 },
  { id: "epl-756", name: "아브라함", nameEn: "Abraham", team: "아스톤 빌라", teamEn: "Aston Villa", position: "FW", cost: 6 },
  { id: "epl-757", name: "지르크제", nameEn: "Zirkzee", team: "맨유", teamEn: "Man Utd", position: "FW", cost: 5.8 },
  { id: "epl-758", name: "이고르 제주스", nameEn: "Igor Jesus", team: "노팅엄", teamEn: "Nott'm Forest", position: "FW", cost: 5.8 },
  { id: "epl-759", name: "윌슨", nameEn: "Wilson", team: "웨스트햄", teamEn: "West Ham", position: "FW", cost: 5.8 },
  { id: "epl-760", name: "배리", nameEn: "Barry", team: "에버턴", teamEn: "Everton", position: "FW", cost: 5.7 },
  { id: "epl-761", name: "칼버트르윈", nameEn: "Calvert-Lewin", team: "리즈", teamEn: "Leeds", position: "FW", cost: 5.7 },
  { id: "epl-762", name: "필크루크", nameEn: "Füllkrug", team: "웨스트햄", teamEn: "West Ham", position: "FW", cost: 5.6 },
  { id: "epl-763", name: "퍼거슨", nameEn: "Ferguson", team: "브라이턴", teamEn: "Brighton", position: "FW", cost: 5.5 },
  { id: "epl-764", name: "우체", nameEn: "Uche", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "FW", cost: 5.5 },
  { id: "epl-765", name: "타티", nameEn: "Taty", team: "웨스트햄", teamEn: "West Ham", position: "FW", cost: 5.5 },
  { id: "epl-766", name: "루카", nameEn: "Lucca", team: "노팅엄", teamEn: "Nott'm Forest", position: "FW", cost: 5.5 },
  { id: "epl-767", name: "에네스 위날", nameEn: "Enes Ünal", team: "본머스", teamEn: "Bournemouth", position: "FW", cost: 5.4 },
  { id: "epl-768", name: "은케티아", nameEn: "Nketiah", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "FW", cost: 5.4 },
  { id: "epl-769", name: "오술라", nameEn: "Osula", team: "뉴캐슬", teamEn: "Newcastle", position: "FW", cost: 5.4 },
  { id: "epl-770", name: "톨루", nameEn: "Tolu", team: "울버햄턴", teamEn: "Wolves", position: "FW", cost: 5.4 },
  { id: "epl-771", name: "브로베이", nameEn: "Brobbey", team: "선덜랜드", teamEn: "Sunderland", position: "FW", cost: 5.4 },
  { id: "epl-772", name: "파블로", nameEn: "Pablo", team: "웨스트햄", teamEn: "West Ham", position: "FW", cost: 5.4 },
  { id: "epl-773", name: "플레밍", nameEn: "Flemming", team: "번리", teamEn: "Burnley", position: "FW", cost: 5.3 },
  { id: "epl-774", name: "무니스", nameEn: "Muniz", team: "풀럼", teamEn: "Fulham", position: "FW", cost: 5.3 },
  { id: "epl-775", name: "암스트롱", nameEn: "Armstrong", team: "울버햄턴", teamEn: "Wolves", position: "FW", cost: 5.3 },
  { id: "epl-776", name: "치마스", nameEn: "Tzimas", team: "브라이턴", teamEn: "Brighton", position: "FW", cost: 5.2 },
  { id: "epl-777", name: "아워니이", nameEn: "Awoniyi", team: "노팅엄", teamEn: "Nott'm Forest", position: "FW", cost: 5.2 },
  { id: "epl-778", name: "마옌다", nameEn: "Mayenda", team: "선덜랜드", teamEn: "Sunderland", position: "FW", cost: 5.2 },
  { id: "epl-779", name: "브로야", nameEn: "Broja", team: "번리", teamEn: "Burnley", position: "FW", cost: 5.2 },
  { id: "epl-780", name: "이시도르", nameEn: "Isidor", team: "선덜랜드", teamEn: "Sunderland", position: "FW", cost: 5.1 },
  { id: "epl-781", name: "에두아르", nameEn: "Édouard", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "FW", cost: 5 },
  { id: "epl-782", name: "베투", nameEn: "Beto", team: "에버턴", teamEn: "Everton", position: "FW", cost: 5 },
  { id: "epl-783", name: "마테오 조셉", nameEn: "Mateo Joseph", team: "리즈", teamEn: "Leeds", position: "FW", cost: 5 },
  { id: "epl-784", name: "은메차", nameEn: "Nmecha", team: "리즈", teamEn: "Leeds", position: "FW", cost: 5 },
  { id: "epl-785", name: "포스터", nameEn: "Foster", team: "번리", teamEn: "Burnley", position: "FW", cost: 4.9 },
  { id: "epl-786", name: "체르미티", nameEn: "Y.Chermiti", team: "에버턴", teamEn: "Everton", position: "FW", cost: 4.9 },
  { id: "epl-787", name: "피로", nameEn: "Piroe", team: "리즈", teamEn: "Leeds", position: "FW", cost: 4.9 },
  { id: "epl-788", name: "뱀포드", nameEn: "Bamford", team: "리즈", teamEn: "Leeds", position: "FW", cost: 4.9 },
  { id: "epl-789", name: "파비우 실바", nameEn: "Fábio Silva", team: "울버햄턴", teamEn: "Wolves", position: "FW", cost: 4.9 },
  { id: "epl-790", name: "칼라이지치", nameEn: "Kalajdžić", team: "울버햄턴", teamEn: "Wolves", position: "FW", cost: 4.9 },
  { id: "epl-791", name: "코스토울라스", nameEn: "Kostoulas", team: "브라이턴", teamEn: "Brighton", position: "FW", cost: 4.8 },
  { id: "epl-792", name: "암두니", nameEn: "Amdouni", team: "번리", teamEn: "Burnley", position: "FW", cost: 4.8 },
  { id: "epl-793", name: "크루피", nameEn: "Kroupi.Jr", team: "본머스", teamEn: "Bournemouth", position: "FW", cost: 4.7 },
  { id: "epl-794", name: "레드몬드", nameEn: "Redmond", team: "아스톤 빌라", teamEn: "Aston Villa", position: "FW", cost: 4.5 },
  { id: "epl-795", name: "위틀리", nameEn: "Wheatley", team: "맨유", teamEn: "Man Utd", position: "FW", cost: 4.5 },
  { id: "epl-796", name: "랭크시어", nameEn: "Lankshear", team: "토트넘", teamEn: "Spurs", position: "FW", cost: 4.5 },
  { id: "epl-797", name: "쿠시아사레", nameEn: "Kusi-Asare", team: "풀럼", teamEn: "Fulham", position: "FW", cost: 4.5 },
  { id: "epl-798", name: "그레이", nameEn: "Gray", team: "리즈", teamEn: "Leeds", position: "FW", cost: 4.5 },
  { id: "epl-799", name: "마네", nameEn: "Mané", team: "울버햄턴", teamEn: "Wolves", position: "FW", cost: 4.5 },
  { id: "epl-800", name: "그레이엄", nameEn: "Graham", team: "에버턴", teamEn: "Everton", position: "FW", cost: 4.5 },
  { id: "epl-801", name: "케이시", nameEn: "Casey", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "FW", cost: 4.5 },
  { id: "epl-802", name: "푸로", nameEn: "Furo", team: "브렌트퍼드", teamEn: "Brentford", position: "FW", cost: 4.5 },
  { id: "epl-803", name: "윌슨", nameEn: "Wilson", team: "토트넘", teamEn: "Spurs", position: "FW", cost: 4.5 },
  { id: "epl-804", name: "아두아제이", nameEn: "Adu-Adjei", team: "본머스", teamEn: "Bournemouth", position: "FW", cost: 4.4 },
  { id: "epl-805", name: "모건", nameEn: "Morgan", team: "브렌트퍼드", teamEn: "Brentford", position: "FW", cost: 4.4 },
  { id: "epl-806", name: "오바페미", nameEn: "Obafemi", team: "번리", teamEn: "Burnley", position: "FW", cost: 4.4 },
  { id: "epl-807", name: "마시", nameEn: "Marsh", team: "크리스탈 팰리스", teamEn: "Crystal Palace", position: "FW", cost: 4.4 },
  { id: "epl-808", name: "셰리프", nameEn: "Sherif", team: "에버턴", teamEn: "Everton", position: "FW", cost: 4.4 },
  { id: "epl-809", name: "루이스 에미르", nameEn: "Luís Hemir", team: "선덜랜드", teamEn: "Sunderland", position: "FW", cost: 4.4 },
  { id: "epl-810", name: "루신", nameEn: "Rusyn", team: "선덜랜드", teamEn: "Sunderland", position: "FW", cost: 4.4 },
  { id: "epl-811", name: "치워미", nameEn: "Chiwome", team: "울버햄턴", teamEn: "Wolves", position: "FW", cost: 4.4 },
  { id: "epl-812", name: "댄스", nameEn: "Danns", team: "리버풀", teamEn: "Liverpool", position: "FW", cost: 4.3 },
  { id: "epl-813", name: "니브", nameEn: "Neave", team: "뉴캐슬", teamEn: "Newcastle", position: "FW", cost: 4.3 },
  { id: "epl-814", name: "스칼렛", nameEn: "Scarlett", team: "토트넘", teamEn: "Spurs", position: "FW", cost: 4.3 },
  { id: "epl-815", name: "마샬", nameEn: "Marshall", team: "웨스트햄", teamEn: "West Ham", position: "FW", cost: 4.3 },
  { id: "epl-816", name: "반스", nameEn: "Barnes", team: "번리", teamEn: "Burnley", position: "FW", cost: 4.2 },
  { id: "epl-817", name: "오비", nameEn: "Obi", team: "맨유", teamEn: "Man Utd", position: "FW", cost: 4.2 },
  { id: "epl-818", name: "압둘라히", nameEn: "Abdullahi", team: "선덜랜드", teamEn: "Sunderland", position: "FW", cost: 4.2 },
  { id: "epl-819", name: "프레이저", nameEn: "Fraser", team: "울버햄턴", teamEn: "Wolves", position: "FW", cost: 4.2 },
  { id: "epl-820", name: "마르크 기우", nameEn: "Marc Guiu", team: "첼시", teamEn: "Chelsea", position: "FW", cost: 4.1 },
]
