// Fenerbahce–Roma incident: full-time 1–1, full-time line 2.5, half-time line 1.5.
export const periodMarkets = [
  [591, "일반", null, null, "draw"],
  [592, "핸디캡", 1, null, "home"],
  [593, "핸디캡", 2, null, "home"],
  [594, "언더오버", null, 2.5, "under"],
  [595, "SUM", null, null, "even"],
  [596, "일반", null, null, "away"],
  [597, "핸디캡", 1, null, "draw"],
  [598, "언더오버", null, 1.5, "under"],
].map(([no, type, handicap, line, result]) => ({
  id: String(no),
  round_id: "round-1",
  game_no: Number(no),
  sport: "축구",
  league_code: "UCL",
  home_team_name: "페네르바흐체SK",
  away_team_name: "AS로마",
  match_time: "2026-09-10T16:45:00.000Z",
  game_type: String(type),
  handicap: handicap as number | null,
  over_under_line: line as number | null,
  result: String(result),
  home_score: 1,
  away_score: 1,
  status: "completed",
  wisetoto_home_score: null,
  wisetoto_away_score: null,
  wisetoto_at: null,
}))
